//Autogenerated using calculateOffsets.py
#define EXPECTED_MEMSIZE 0xcafebaba
#define EXPECTED_TEXT_HASH 0xcafebabe
#define EXPECTED_DATA_HASH 0xcafedada
#define NUM_SKIPS 0
TextProtectSkip skips[NUM_SKIPS] = {  };
